GET http://localhost:3000/products.json

###
GET http://localhost:3000/products/4.json


###
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "test",
  "price": 20000,
  "image_url": "Test url",
  "description": "x"
}


###
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Lampshade",
  "price": 110,
  "image_url": "Image",
  "description": "What can you do with this?"
}

# ###
# POST http://localhost:3000/products
# Content-Type: application/json

# {
#   "name":,
#   "price": ,
#   "image_url": ,
#   "description": 
# }

####
PATCH http://localhost:3000/products/4.json
Content-Type: application/json

{
  "price": 200
}

###
DELETE http://localhost:3000/products/3

###
POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
  "name": "Lampshade",
  "email": "lampshades@test.com",
  "phone_number": "617-900-9872"
}

###
PATCH http://localhost:3000/suppliers/4.json
Content-Type: application/json

{
  "name": "Lampshades"
}

###
GET http://localhost:3000/suppliers.json 

###
GET http://localhost:3000/suppliers/4.json 
