GET http://localhost:3000/products.json

###
GET http://localhost:3000/products/4.json


###
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "test",
  "price": 20000,
  "image_url": "Test url",
  "description": "x"
}


###
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Lampshade",
  "price": 110,
  "image_url": "Image",
  "description": "What can you do with this?"
}

# ###
# POST http://localhost:3000/products
# Content-Type: application/json

# {
#   "name":,
#   "price": ,
#   "image_url": ,
#   "description": 
# }

####
PATCH http://localhost:3000/products/4.json
Content-Type: application/json

{
  "price": 200
}

###
DELETE http://localhost:3000/products/3

###
POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
  "name": "Lampshade",
  "email": "lampshades@test.com",
  "phone_number": "617-900-9872"
}

###
PATCH http://localhost:3000/suppliers/4.json
Content-Type: application/json

{
  "name": "Lampshades"
}

###
GET http://localhost:3000/suppliers.json 

###
GET http://localhost:3000/suppliers/4.json 


### Create new image
POST http://localhost:3000/images.json 
Content-Type: application/json 

{
  "url": "https://i.etsystatic.com/17498104/r/il/373407/3008335036/il_1588xN.3008335036_eqbt.jpg",
  "product_id": 9,
  "description": "It is what it is"
}

### Create a new order
POST http://localhost:3000/orders.json 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Njg0Mzk4MzB9.7JizAXqIxBVnS8B8xRdr03h2A9ZrMy_3BPUw4I52ZbU

{
  "product_id": 1,
  "quantity": 2
}

###

#### Show one order
GET http://localhost:3000/orders/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Njg0Mzk4MzB9.7JizAXqIxBVnS8B8xRdr03h2A9ZrMy_3BPUw4I52ZbU
Content-Type: application/json

{
  "order_id": 1
}


###

### Show all orders (index)
GET http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Njg0Mzk4MzB9.7JizAXqIxBVnS8B8xRdr03h2A9ZrMy_3BPUw4I52ZbU

####

##Create new user
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Nelson",
  "email": "nelson1214@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "nelson1214@test.com",
  "password": "password"
}

### Check if login is working by pp current_user from products#index route, shows up in terminal
GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Njg0Mzk4MzB9.7JizAXqIxBVnS8B8xRdr03h2A9ZrMy_3BPUw4I52ZbU
